### ISSUE TITLE
unistd.h Macros

### ISSUE THREAD

**Issue by Codelax** [anothergroup/alibc#71]
The <unistd.h> header shall define the following symbolic constants. The values shall be suitable for use in #if preprocessing directives.

_POSIX_VERSION
    Integer value indicating version of this standard (C-language binding) to which the implementation conforms. For implementations conforming to POSIX.1-2017, the value shall be 200809L.
_POSIX2_VERSION
    Integer value indicating version of the Shell and Utilities volume of POSIX.1 to which the implementation conforms. For implementations conforming to POSIX.1-2017, the value shall be 200809L. For profile implementations that define _POSIX_SUBPROFILE (see Subprofiling Considerations) in <unistd.h>, _POSIX2_VERSION may be left undefined or be defined with the value -1 to indicate that the Shell and Utilities volume of POSIX.1 is not supported. In this case, a call to sysconf(_SC_2_VERSION) shall return either 200809L or -1 indicating that the Shell and Utilities volume of POSIX.1 is or is not, respectively, supported at runtime.

The <unistd.h> header shall define the following symbolic constant only if the implementation supports the XSI option; see XSI Conformance. If defined, its value shall be suitable for use in #if preprocessing directives.

_XOPEN_VERSION
    Integer value indicating version of the X/Open Portability Guide to which the implementation conforms. The value shall be 700.

**Comment by Oursin** [comment]
Done in 73ab3eceddb3cf26a84b3941156e2c565e18619b
