### ISSUE TITLE
Unistd.h Constans for Options

### ISSUE THREAD

**Issue by Codelax** [anothergroup/alibc#76]
The following symbolic constants, if defined in <unistd.h>, shall have a value of -1, 0, or greater, unless otherwise specified below. For profile implementations that define _POSIX_SUBPROFILE (see Subprofiling Considerations) in <unistd.h>, constants described below as always having a value greater than zero need not be defined and, if defined, may have a value of -1, 0, or greater. The values shall be suitable for use in #if preprocessing directives.

If a symbolic constant is not defined or is defined with the value -1, the option is not supported for compilation. If it is defined with a value greater than zero, the option shall always be supported when the application is executed. If it is defined with the value zero, the option shall be supported for compilation and might or might not be supported at runtime. See Options for further information about the conformance requirements of these three categories of support.

_POSIX_ADVISORY_INFO
    The implementation supports the Advisory Information option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_ASYNCHRONOUS_IO
    The implementation supports asynchronous input and output. This symbol shall always be set to the value 200809L.
_POSIX_BARRIERS
    The implementation supports barriers. This symbol shall always be set to the value 200809L.
_POSIX_CHOWN_RESTRICTED
    The use of chown() and fchown() is restricted to a process with appropriate privileges, and to changing the group ID of a file only to the effective group ID of the process or to one of its supplementary group IDs. This symbol shall be defined with a value other than -1.
_POSIX_CLOCK_SELECTION
    The implementation supports clock selection. This symbol shall always be set to the value 200809L.
_POSIX_CPUTIME
    The implementation supports the Process CPU-Time Clocks option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_FSYNC
    The implementation supports the File Synchronization option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_IPV6
    The implementation supports the IPv6 option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_JOB_CONTROL
    The implementation supports job control. This symbol shall always be set to a value greater than zero.
_POSIX_MAPPED_FILES
    The implementation supports memory mapped Files. This symbol shall always be set to the value 200809L.
_POSIX_MEMLOCK
    The implementation supports the Process Memory Locking option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_MEMLOCK_RANGE
    The implementation supports the Range Memory Locking option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_MEMORY_PROTECTION
    The implementation supports memory protection. This symbol shall always be set to the value 200809L.
_POSIX_MESSAGE_PASSING
    The implementation supports the Message Passing option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_MONOTONIC_CLOCK
    The implementation supports the Monotonic Clock option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_NO_TRUNC
    Pathname components longer than {NAME_MAX} generate an error. This symbol shall be defined with a value other than -1.
_POSIX_PRIORITIZED_IO
    The implementation supports the Prioritized Input and Output option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_PRIORITY_SCHEDULING
    The implementation supports the Process Scheduling option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_RAW_SOCKETS
    The implementation supports the Raw Sockets option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_READER_WRITER_LOCKS
    The implementation supports read-write locks. This symbol shall always be set to the value 200809L.
_POSIX_REALTIME_SIGNALS
    The implementation supports realtime signals. This symbol shall always be set to the value 200809L.
_POSIX_REGEXP
    The implementation supports the Regular Expression Handling option. This symbol shall always be set to a value greater than zero.
_POSIX_SAVED_IDS
    Each process has a saved set-user-ID and a saved set-group-ID. This symbol shall always be set to a value greater than zero.
_POSIX_SEMAPHORES
    The implementation supports semaphores. This symbol shall always be set to the value 200809L.
_POSIX_SHARED_MEMORY_OBJECTS
    The implementation supports the Shared Memory Objects option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_SHELL
    The implementation supports the POSIX shell. This symbol shall always be set to a value greater than zero.
_POSIX_SPAWN
    The implementation supports the Spawn option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_SPIN_LOCKS
    The implementation supports spin locks. This symbol shall always be set to the value 200809L.
_POSIX_SPORADIC_SERVER
    The implementation supports the Process Sporadic Server option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_SYNCHRONIZED_IO
    The implementation supports the Synchronized Input and Output option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_THREAD_ATTR_STACKADDR
    The implementation supports the Thread Stack Address Attribute option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_THREAD_ATTR_STACKSIZE
    The implementation supports the Thread Stack Size Attribute option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_THREAD_CPUTIME
    The implementation supports the Thread CPU-Time Clocks option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_THREAD_PRIO_INHERIT
    The implementation supports the Non-Robust Mutex Priority Inheritance option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_THREAD_PRIO_PROTECT
    The implementation supports the Non-Robust Mutex Priority Protection option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_THREAD_PRIORITY_SCHEDULING
    The implementation supports the Thread Execution Scheduling option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_THREAD_PROCESS_SHARED
    The implementation supports the Thread Process-Shared Synchronization option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_THREAD_ROBUST_PRIO_INHERIT
    The implementation supports the Robust Mutex Priority Inheritance option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_THREAD_ROBUST_PRIO_PROTECT
    The implementation supports the Robust Mutex Priority Protection option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_THREAD_SAFE_FUNCTIONS
    The implementation supports thread-safe functions. This symbol shall always be set to the value 200809L.
_POSIX_THREAD_SPORADIC_SERVER
    The implementation supports the Thread Sporadic Server option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_THREADS
    The implementation supports threads. This symbol shall always be set to the value 200809L.
_POSIX_TIMEOUTS
    The implementation supports timeouts. This symbol shall always be set to the value 200809L.
_POSIX_TIMERS
    The implementation supports timers. This symbol shall always be set to the value 200809L.
_POSIX_TRACE
    The implementation supports the Trace option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_TRACE_EVENT_FILTER
    The implementation supports the Trace Event Filter option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_TRACE_INHERIT
    The implementation supports the Trace Inherit option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_TRACE_LOG
    The implementation supports the Trace Log option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_TYPED_MEMORY_OBJECTS
    The implementation supports the Typed Memory Objects option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX_V6_ILP32_OFF32
    The implementation provides a C-language compilation environment with 32-bit int, long, pointer, and off_t types.
_POSIX_V6_ILP32_OFFBIG
    The implementation provides a C-language compilation environment with 32-bit int, long, and pointer types and an off_t type using at least 64 bits.
_POSIX_V6_LP64_OFF64
    The implementation provides a C-language compilation environment with 32-bit int and 64-bit long, pointer, and off_t types.
_POSIX_V6_LPBIG_OFFBIG
    The implementation provides a C-language compilation environment with an int type using at least 32 bits and long, pointer, and off_t types using at least 64 bits. [Option End]
_POSIX_V7_ILP32_OFF32
    The implementation provides a C-language compilation environment with 32-bit int, long, pointer, and off_t types.
_POSIX_V7_ILP32_OFFBIG
    The implementation provides a C-language compilation environment with 32-bit int, long, and pointer types and an off_t type using at least 64 bits.
_POSIX_V7_LP64_OFF64
    The implementation provides a C-language compilation environment with 32-bit int and 64-bit long, pointer, and off_t types.
_POSIX_V7_LPBIG_OFFBIG
    The implementation provides a C-language compilation environment with an int type using at least 32 bits and long, pointer, and off_t types using at least 64 bits.
_POSIX2_C_BIND
    The implementation supports the C-Language Binding option. This symbol shall always have the value 200809L.
_POSIX2_C_DEV
    The implementation supports the C-Language Development Utilities option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L. [Option End]
_POSIX2_CHAR_TERM
    The implementation supports the Terminal Characteristics option. The value of this symbol reported by sysconf() shall either be -1 or a value greater than zero.
_POSIX2_FORT_DEV
    The implementation supports the FORTRAN Development Utilities option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX2_FORT_RUN
    The implementation supports the FORTRAN Runtime Utilities option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX2_LOCALEDEF
    The implementation supports the creation of locales by the localedef utility. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX2_PBS
    The implementation supports the Batch Environment Services and Utilities option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX2_PBS_ACCOUNTING
    The implementation supports the Batch Accounting option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX2_PBS_CHECKPOINT
    The implementation supports the Batch Checkpoint/Restart option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX2_PBS_LOCATE
    The implementation supports the Locate Batch Job Request option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX2_PBS_MESSAGE
    The implementation supports the Batch Job Message Request option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX2_PBS_TRACK
    The implementation supports the Track Batch Job Request option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX2_SW_DEV
    The implementation supports the Software Development Utilities option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_POSIX2_UPE
    The implementation supports the User Portability Utilities option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall either be -1 or 200809L.
_XOPEN_CRYPT
    The implementation supports the X/Open Encryption Option Group.
_XOPEN_ENH_I18N
    The implementation supports the Issue 4, Version 2 Enhanced Internationalization Option Group. This symbol shall always be set to a value other than -1.
_XOPEN_REALTIME
    The implementation supports the X/Open Realtime Option Group.
_XOPEN_REALTIME_THREADS
    The implementation supports the X/Open Realtime Threads Option Group.
_XOPEN_SHM
    The implementation supports the Issue 4, Version 2 Shared Memory Option Group. This symbol shall always be set to a value other than -1.
_XOPEN_STREAMS
    The implementation supports the XSI STREAMS Option Group.
_XOPEN_UNIX
    The implementation supports the XSI option.
_XOPEN_UUCP
    The implementation supports the UUCP Utilities option. If this symbol is defined in <unistd.h>, it shall be defined to be -1, 0, or 200809L. The value of this symbol reported by sysconf() shall be either -1 or 200809L.

**Comment by Oursin** [comment]
Done in 73ab3eceddb3cf26a84b3941156e2c565e18619b
